### ISSUE TITLE
Missing libxfoil dependency

### ISSUE THREAD

**Issue by grgoon** [byuflowlab/Xfoil.jl#5]
Hi, I have this error when trying to build Xfoil. I have also complied libxfoil separately but couldn't figure out how to have it added as a Julia dependency. Would you help, please? I'm using Windows.

Error: Error building `Xfoil`: 
│ ERROR: LoadError: None of the selected providers can install dependency libxfoil.
│ Use BinDeps.debug(package_name) to see available providers
│ 
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\grgoo\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:956  
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\grgoo\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:929
│  [4] top-level scope at C:\Users\grgoo\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:984
│  [5] include(::String) at .\client.jl:439
│  [6] top-level scope at none:5
│ in expression starting at C:\Users\grgoo\.julia\packages\Xfoil\8wAJo\deps\build.jl:32
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:899

**Comment by taylormcd** [comment]
Ideally you wouldn't have to build the shared library at all, BinDeps should build and load the shared library for you.  The real issue here is that I currently don't have a method implemented for building the shared library dependency on Windows.

**Comment by taylormcd** [comment]
As a workaround, just replace the section "Get XFOIL libraries" section in src/Xfoil.jl with 
```
const libxfoil = "/path/to/your/compiled/float/library.dll"
const libxfoil_cs = "/path/to/your/compiled/complex/library.dll"
```

**Comment by grgoon** [comment]
I tried replacing the "Get XFOIL libraries section in src/Xfoil.jl and receive the following error:

ERROR: LoadError: InitError: could not load library "C:/..../libxfoil.dll"
%1 is not a valid Win32 application.

**Comment by grgoon** [comment]
I am also trying to install this on my mac, but it also failed at libxfoil. 

Error: Error building `Xfoil`: 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xfoil.f -o xfoil.o
│ 
│         --- Compiled xfoil.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xpanel.f -o xpanel.o
│ 
│         --- Compiled xpanel.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xoper.f -o xoper.o
│ 
│         --- Compiled xoper.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xsolve.f -o xsolve.o
│ 
│         --- Compiled xsolve.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xgdes.f -o xgdes.o
│ 
│         --- Compiled xgdes.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xbl.f -o xbl.o
│ 
│         --- Compiled xbl.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xblsys.f -o xblsys.o
│ 
│         --- Compiled xblsys.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xgeom.f -o xgeom.o
│ 
│         --- Compiled xgeom.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xutils.f -o xutils.o
│ 
│         --- Compiled xutils.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c aread.f -o aread.o
│ 
│         --- Compiled aread.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c userio.f -o userio.o
│ 
│         --- Compiled userio.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c spline.f -o spline.o
│ 
│         --- Compiled spline.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c naca.f -o naca.o
│ 
│         --- Compiled naca.f successfully ---
│ 
│ gfortran -O3 -fdefault-real-8 -fPIC -shared -c xdriver.f -o xdriver.o
│ 
│         --- Compiled xdriver.f successfully ---
│ 
│ gfortran -O3 -shared -fPIC -o libxfoil.dylib xfoil.o xpanel.o xoper.o xsolve.o xgdes.o xbl.o xblsys.o xgeom.o xutils.o aread.o userio.o spline.o naca.o xdriver.o
│ install libxfoil.dylib /Users/Grace/.julia/packages/Xfoil/8wAJo/deps/usr/lib
│ [ Info: Changing directory to /Users/Grace/.julia/packages/Xfoil/8wAJo/deps/src/xfoil
│ [ Info: Changing directory to /Users/Grace/.julia/packages/Xfoil/8wAJo/deps/src/xfoil
│ ERROR: LoadError: Provider BuildProcess failed to satisfy dependency libxfoil
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /Users/Grace/.julia/packages/BinDeps/ZEval/src/dependencies.jl:945
│  [3] satisfy!(::BinDeps.LibraryDependency) at /Users/Grace/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [4] top-level scope at /Users/Grace/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [5] include(::String) at ./client.jl:457
│  [6] top-level scope at none:5
│ in expression starting at /Users/Grace/.julia/packages/Xfoil/8wAJo/deps/build.jl:32
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:942

**Comment by taylormcd** [comment]
I'm working towards constructing a Xfoil_JLL package using BinaryBuilder, which should alleviate all these build process problems and make this package work on more architectures.

**Comment by taylormcd** [comment]
Good news.  This package should work on most systems now thanks to prepackaged binaries built using BinaryBuilder.  No build steps required.
